bookName: "§eExample"
bookAuthor: "§bSomeone"
line1: "§6InfoBook §a1.0 §6by §aPetteriM1"
line2: "§3Edit text of this book in config.yml"
line3: ""
line4: ""
line5: ""
line6: ""
line7: ""
line8: ""
line9: ""
line10: ""
line11: ""
line12: ""
line13: ""
line14: ""
line15: ""
line16: ""
line17: ""
line18: ""
line19: ""
line20: ""